import { Complaint, MaintenanceTeam, NotificationItem } from '../types';

export const INITIAL_MAINTENANCE_TEAMS: MaintenanceTeam[] = [
  {
    id: 'team-a',
    name: 'Electrical Maintenance Team A',
    members: ['Rajesh Sharma (Lead)', 'Vikram Singh', 'Rohan Patel'],
    currentAssignmentsCount: 2,
    availability: 'Available',
    area: 'Mira Road North & Sectors',
    phone: '+91 98201 55431',
    lead: 'Rajesh Sharma',
  },
  {
    id: 'team-b',
    name: 'Electrical Maintenance Team B',
    members: ['Amit Patel (Lead)', 'Suresh Kumar', 'Sunil Pawar'],
    currentAssignmentsCount: 3,
    availability: 'Busy',
    area: 'Bhayandar East & Industrial Zone',
    phone: '+91 98202 88123',
    lead: 'Amit Patel',
  },
  {
    id: 'team-c',
    name: 'Public Lighting Team',
    members: ['Anil Verma (Lead)', 'Manoj Kumar', 'Pankaj Mehta'],
    currentAssignmentsCount: 1,
    availability: 'Available',
    area: 'Mira Road West & Bhayandar West',
    phone: '+91 98203 44901',
    lead: 'Anil Verma',
  },
  {
    id: 'team-d',
    name: 'Emergency Response Team',
    members: ['Deepak Rao (Lead)', 'Sandeep Patil', 'Ganesh Jadhav'],
    currentAssignmentsCount: 2,
    availability: 'On Shift',
    area: 'Citywide High Hazard Unit',
    phone: '+91 98200 10099',
    lead: 'Deepak Rao',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'URJ-2026-00101',
    issueType: 'Streetlight Not Working',
    description: 'Main street light near Sector 10 park entrance has been completely non-functional for 3 consecutive days. Area is very dark at night causing safety concerns for pedestrians.',
    location: 'Mira Road Sector 10, Near Sector Park Gate #2',
    area: 'Mira Road Sector 10',
    ward: 'Ward 4',
    pincode: '401107',
    priority: 'High',
    status: 'RESOLVED',
    reportedDate: '2026-09-28T10:42:00.000Z',
    lastUpdated: '2026-09-29T16:30:00.000Z',
    assignedTeam: 'Electrical Maintenance Team A',
    reportedBy: {
      name: 'Aarav Mehta',
      phone: '+91 98765 43210',
      email: 'aarav.m@example.com',
    },
    coordinates: { lat: 19.2812, lng: 72.8561 },
    timeline: [
      {
        id: 'tl-101-1',
        status: 'REPORTED',
        message: 'Citizen reported non-working streetlight with location details.',
        timestamp: '2026-09-28T10:42:00.000Z',
        actor: 'Aarav Mehta (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-101-2',
        status: 'VERIFIED',
        message: 'Complaint verified by Urban Energy Administration desk.',
        timestamp: '2026-09-28T11:15:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'status_change',
      },
      {
        id: 'tl-101-3',
        status: 'ASSIGNED',
        message: 'Assigned to Electrical Maintenance Team A.',
        timestamp: '2026-09-28T12:05:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'assignment',
      },
      {
        id: 'tl-101-4',
        status: 'WORK IN PROGRESS',
        message: 'Maintenance team arrived on site and started LED fixture replacement.',
        timestamp: '2026-09-28T14:20:00.000Z',
        actor: 'Electrical Maintenance Team A',
        type: 'status_change',
      },
      {
        id: 'tl-101-5',
        status: 'RESOLVED',
        message: 'LED driver and bulb replaced. Illumination tested and verified operational.',
        timestamp: '2026-09-29T16:30:00.000Z',
        actor: 'Electrical Maintenance Team A',
        type: 'status_change',
      },
    ],
    updates: [
      {
        id: 'up-101-1',
        message: 'Team dispatched with replacement 100W LED streetlight fixture.',
        timestamp: '2026-09-28T12:15:00.000Z',
        author: 'Electrical Maintenance Team A',
      },
      {
        id: 'up-101-2',
        message: 'Defective capacitor removed; tested wiring integrity.',
        timestamp: '2026-09-28T15:10:00.000Z',
        author: 'Rajesh Sharma (Lead)',
      },
    ],
  },
  {
    id: 'URJ-2026-00102',
    issueType: 'Streetlight Flickering',
    description: 'High-intensity light on main arterial road keeps rapidly flickering every few seconds, creating severe glare and distraction for night drivers.',
    location: 'Station Road, Near East Bus Depot',
    area: 'Bhayandar East',
    ward: 'Ward 2',
    pincode: '401105',
    priority: 'Medium',
    status: 'WORK IN PROGRESS',
    reportedDate: '2026-09-29T08:15:00.000Z',
    lastUpdated: '2026-09-30T09:10:00.000Z',
    assignedTeam: 'Electrical Maintenance Team B',
    reportedBy: {
      name: 'Priya Sharma',
      phone: '+91 98112 33445',
      email: 'priya.s@example.com',
    },
    coordinates: { lat: 19.2945, lng: 72.8512 },
    timeline: [
      {
        id: 'tl-102-1',
        status: 'REPORTED',
        message: 'Citizen reported rapidly flickering public light on arterial road.',
        timestamp: '2026-09-29T08:15:00.000Z',
        actor: 'Priya Sharma (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-102-2',
        status: 'VERIFIED',
        message: 'Complaint verified after cross-checking feeder line logs.',
        timestamp: '2026-09-29T09:30:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'status_change',
      },
      {
        id: 'tl-102-3',
        status: 'ASSIGNED',
        message: 'Assigned to Electrical Maintenance Team B.',
        timestamp: '2026-09-29T10:45:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'assignment',
      },
      {
        id: 'tl-102-4',
        status: 'WORK IN PROGRESS',
        message: 'Team investigating loose neutral wire at local junction box.',
        timestamp: '2026-09-30T09:10:00.000Z',
        actor: 'Electrical Maintenance Team B',
        type: 'status_change',
      },
    ],
    updates: [
      {
        id: 'up-102-1',
        message: 'Inspection confirmed loose connection in junction terminal box #14.',
        timestamp: '2026-09-30T09:12:00.000Z',
        author: 'Amit Patel (Lead)',
      },
    ],
  },
  {
    id: 'URJ-2026-00103',
    issueType: 'Damaged Electrical Pole',
    description: 'Electric utility pole tilted at roughly 25 degrees following heavy vehicle impact. Cables hanging low across pedestrian sidewalk.',
    location: 'Mira Bhayandar Road, Opposite Silver Park',
    area: 'Mira Road East',
    ward: 'Ward 7',
    pincode: '401107',
    priority: 'Critical',
    status: 'VERIFIED',
    reportedDate: '2026-09-30T11:00:00.000Z',
    lastUpdated: '2026-09-30T11:45:00.000Z',
    assignedTeam: 'Emergency Response Team',
    reportedBy: {
      name: 'Rohan Gupta',
      phone: '+91 97690 12345',
      email: 'rohan.g@example.com',
    },
    coordinates: { lat: 19.2891, lng: 72.8624 },
    timeline: [
      {
        id: 'tl-103-1',
        status: 'REPORTED',
        message: 'Critical safety hazard reported: Tilted electrical pole with sagging conductors.',
        timestamp: '2026-09-30T11:00:00.000Z',
        actor: 'Rohan Gupta (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-103-2',
        status: 'VERIFIED',
        message: 'High priority hazard verified by control room operator. Emergency protocols triggered.',
        timestamp: '2026-09-30T11:45:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'status_change',
      },
    ],
    updates: [],
  },
  {
    id: 'URJ-2026-00104',
    issueType: 'Streetlight Not Working',
    description: 'Three consecutive streetlights are non-operational along the coastal road stretch.',
    location: 'Uttan Road, Near West View Apartments',
    area: 'Bhayandar West',
    ward: 'Ward 1',
    pincode: '401101',
    priority: 'High',
    status: 'ASSIGNED',
    reportedDate: '2026-09-29T14:20:00.000Z',
    lastUpdated: '2026-09-29T16:00:00.000Z',
    assignedTeam: 'Public Lighting Team',
    reportedBy: {
      name: 'Sunita Deshmukh',
      phone: '+91 98334 55667',
      email: 'sunita.d@example.com',
    },
    coordinates: { lat: 19.3012, lng: 72.8398 },
    timeline: [
      {
        id: 'tl-104-1',
        status: 'REPORTED',
        message: 'Citizen reported multiple dark streetlights on Uttan Road stretch.',
        timestamp: '2026-09-29T14:20:00.000Z',
        actor: 'Sunita Deshmukh (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-104-2',
        status: 'VERIFIED',
        message: 'Complaint verified.',
        timestamp: '2026-09-29T15:10:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'status_change',
      },
      {
        id: 'tl-104-3',
        status: 'ASSIGNED',
        message: 'Assigned to Public Lighting Team for morning audit.',
        timestamp: '2026-09-29T16:00:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'assignment',
      },
    ],
    updates: [],
  },
  {
    id: 'URJ-2026-00105',
    issueType: 'Exposed Electrical Wiring',
    description: 'Base access door of streetlight pole #42 is missing. Live bare wires visible and exposed near childrens play area ground.',
    location: 'Kashimira Flyover Junction Park',
    area: 'Kashimira Junction',
    ward: 'Ward 9',
    pincode: '401107',
    priority: 'Critical',
    status: 'WORK IN PROGRESS',
    reportedDate: '2026-09-30T07:30:00.000Z',
    lastUpdated: '2026-09-30T08:45:00.000Z',
    assignedTeam: 'Emergency Response Team',
    reportedBy: {
      name: 'Vikram Thorne',
      phone: '+91 98200 44321',
      email: 'vikram.t@example.com',
    },
    coordinates: { lat: 19.2741, lng: 72.8710 },
    timeline: [
      {
        id: 'tl-105-1',
        status: 'REPORTED',
        message: 'Exposed live wiring reported near park play zone.',
        timestamp: '2026-09-30T07:30:00.000Z',
        actor: 'Vikram Thorne (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-105-2',
        status: 'VERIFIED',
        message: 'Verified critical safety alert.',
        timestamp: '2026-09-30T07:45:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'status_change',
      },
      {
        id: 'tl-105-3',
        status: 'ASSIGNED',
        message: 'Assigned immediately to Emergency Response Team.',
        timestamp: '2026-09-30T07:50:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'assignment',
      },
      {
        id: 'tl-105-4',
        status: 'WORK IN PROGRESS',
        message: 'Emergency crew on site placing safety barricades and insulating exposed terminals.',
        timestamp: '2026-09-30T08:45:00.000Z',
        actor: 'Emergency Response Team',
        type: 'status_change',
      },
    ],
    updates: [
      {
        id: 'up-105-1',
        message: 'Safety tape installed around pole base; power safely isolated at feeder pillar.',
        timestamp: '2026-09-30T08:50:00.000Z',
        author: 'Deepak Rao (Lead)',
      },
    ],
  },
  {
    id: 'URJ-2026-00106',
    issueType: 'Public Lighting Damage',
    description: 'Decorative garden pole light glass casing shattered, bulb broken.',
    location: 'Beverly Park Central Jogging Track',
    area: 'Beverly Park',
    ward: 'Ward 5',
    pincode: '401107',
    priority: 'Low',
    status: 'REPORTED',
    reportedDate: '2026-09-30T10:15:00.000Z',
    lastUpdated: '2026-09-30T10:15:00.000Z',
    reportedBy: {
      name: 'Kavita Iyer',
      phone: '+91 99301 22890',
      email: 'kavita.i@example.com',
    },
    coordinates: { lat: 19.2834, lng: 72.8590 },
    timeline: [
      {
        id: 'tl-106-1',
        status: 'REPORTED',
        message: 'Citizen submitted report with photograph of shattered glass casing.',
        timestamp: '2026-09-30T10:15:00.000Z',
        actor: 'Kavita Iyer (Citizen)',
        type: 'creation',
      },
    ],
    updates: [],
  },
  {
    id: 'URJ-2026-00107',
    issueType: 'Electrical Infrastructure Issue',
    description: 'Feeder pillar box door hanging loose with broken latch.',
    location: 'Kanakia Road, Near Joggers Park',
    area: 'Kanakia Park',
    ward: 'Ward 3',
    pincode: '401107',
    priority: 'Medium',
    status: 'RESOLVED',
    reportedDate: '2026-09-27T11:20:00.000Z',
    lastUpdated: '2026-09-28T15:00:00.000Z',
    assignedTeam: 'Electrical Maintenance Team A',
    reportedBy: {
      name: 'Siddharth Rao',
      phone: '+91 98670 99887',
      email: 'siddharth.r@example.com',
    },
    coordinates: { lat: 19.2870, lng: 72.8540 },
    timeline: [
      {
        id: 'tl-107-1',
        status: 'REPORTED',
        message: 'Report submitted.',
        timestamp: '2026-09-27T11:20:00.000Z',
        actor: 'Siddharth Rao (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-107-2',
        status: 'RESOLVED',
        message: 'Latch repaired and lock replaced by maintenance team.',
        timestamp: '2026-09-28T15:00:00.000Z',
        actor: 'Electrical Maintenance Team A',
        type: 'status_change',
      },
    ],
    updates: [],
  },
  {
    id: 'URJ-2026-00108',
    issueType: 'Streetlight Flickering',
    description: 'Low intensity light flickering intermittently during evening hours.',
    location: 'Shanti Nagar Sector 3, Street 5',
    area: 'Shanti Nagar',
    ward: 'Ward 6',
    pincode: '401107',
    priority: 'Low',
    status: 'VERIFIED',
    reportedDate: '2026-09-30T06:40:00.000Z',
    lastUpdated: '2026-09-30T09:20:00.000Z',
    reportedBy: {
      name: 'Nikhil Shah',
      phone: '+91 98211 77665',
      email: 'nikhil.s@example.com',
    },
    coordinates: { lat: 19.2855, lng: 72.8610 },
    timeline: [
      {
        id: 'tl-108-1',
        status: 'REPORTED',
        message: 'Reported by citizen.',
        timestamp: '2026-09-30T06:40:00.000Z',
        actor: 'Nikhil Shah (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-108-2',
        status: 'VERIFIED',
        message: 'Verified by system admin.',
        timestamp: '2026-09-30T09:20:00.000Z',
        actor: 'Urban Energy Admin',
        type: 'status_change',
      },
    ],
    updates: [],
  },
  {
    id: 'URJ-2026-00109',
    issueType: 'Damaged Electrical Pole',
    description: 'Cracked concrete base on streetlight pole after storm.',
    location: 'Silver Park Main Avenue',
    area: 'Silver Park',
    ward: 'Ward 8',
    pincode: '401107',
    priority: 'High',
    status: 'WORK IN PROGRESS',
    reportedDate: '2026-09-29T16:10:00.000Z',
    lastUpdated: '2026-09-30T10:00:00.000Z',
    assignedTeam: 'Emergency Response Team',
    reportedBy: {
      name: 'Ananya Roy',
      phone: '+91 97731 44556',
      email: 'ananya.r@example.com',
    },
    coordinates: { lat: 19.2905, lng: 72.8655 },
    timeline: [
      {
        id: 'tl-109-1',
        status: 'REPORTED',
        message: 'Cracked pole base reported.',
        timestamp: '2026-09-29T16:10:00.000Z',
        actor: 'Ananya Roy (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-109-2',
        status: 'WORK IN PROGRESS',
        message: 'Reinforcement support being installed.',
        timestamp: '2026-09-30T10:00:00.000Z',
        actor: 'Emergency Response Team',
        type: 'status_change',
      },
    ],
    updates: [],
  },
  {
    id: 'URJ-2026-00110',
    issueType: 'Streetlight Not Working',
    description: 'Sodium lamp failed, street completely dark.',
    location: 'Station Road East Market Plaza',
    area: 'Station Road East',
    ward: 'Ward 2',
    pincode: '401105',
    priority: 'Medium',
    status: 'RESOLVED',
    reportedDate: '2026-09-26T19:00:00.000Z',
    lastUpdated: '2026-09-27T14:30:00.000Z',
    assignedTeam: 'Public Lighting Team',
    reportedBy: {
      name: 'Manish Pandey',
      phone: '+91 98920 11223',
      email: 'manish.p@example.com',
    },
    coordinates: { lat: 19.2960, lng: 72.8530 },
    timeline: [
      {
        id: 'tl-110-1',
        status: 'REPORTED',
        message: 'Sodium lamp failure reported.',
        timestamp: '2026-09-26T19:00:00.000Z',
        actor: 'Manish Pandey (Citizen)',
        type: 'creation',
      },
      {
        id: 'tl-110-2',
        status: 'RESOLVED',
        message: 'Replaced sodium lamp with energy-efficient 80W LED bulb.',
        timestamp: '2026-09-27T14:30:00.000Z',
        actor: 'Public Lighting Team',
        type: 'status_change',
      },
    ],
    updates: [],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    complaintId: 'URJ-2026-00101',
    title: 'Complaint Resolved',
    message: 'Your reported streetlight issue URJ-2026-00101 at Mira Road Sector 10 has been successfully resolved!',
    timestamp: '2026-09-29T16:30:00.000Z',
    read: false,
    type: 'resolution',
  },
  {
    id: 'notif-2',
    complaintId: 'URJ-2026-00102',
    title: 'Work Started',
    message: 'Electrical Maintenance Team B has started work on URJ-2026-00102.',
    timestamp: '2026-09-30T09:10:00.000Z',
    read: false,
    type: 'status_update',
  },
  {
    id: 'notif-3',
    complaintId: 'URJ-2026-00105',
    title: 'Emergency Team Assigned',
    message: 'URJ-2026-00105 assigned to Emergency Response Team.',
    timestamp: '2026-09-30T07:50:00.000Z',
    read: true,
    type: 'assignment',
  },
];
